### Load in NumPy (remember to pip install numpy first)

### import numpy as np  

### The Basics

In [6]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [7]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

# Get Dimension

print(a.ndim)

[1 2 3]
1


In [8]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

# Get Type

print(a.dtype)

[1 2 3]
int32


In [9]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

# Get Size

print(a.itemsize)

[1 2 3]
4


In [10]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

# Get total size

print(a.nbytes)

[1 2 3]
12


In [11]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

# Get number of elements

print(a.size)

[1 2 3]
3


In [12]:
import numpy as np
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
import numpy as np
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

# Get Shape
print(b.shape)

(2, 3)


### Accessing/Changing specific elements, rows, columns, etc

In [14]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r, c]
a[1, 5]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


13

In [18]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific row 
a[0, :]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([1, 2, 3, 4, 5, 6, 7])

In [19]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific column
a[:, 2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([ 3, 10])

In [20]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

In [21]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [22]:
import numpy as np

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
import numpy as np

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# Get specific element (work outside in)
b[0,1,1]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
import numpy as np

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# replace 

b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [30]:
import numpy as np

# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
import numpy as np

# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
import numpy as np

# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [33]:
import numpy as np

# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
import numpy as np

# Random decimal numbers
np.random.rand(4,2)

array([[0.05401868, 0.46119642],
       [0.23790263, 0.81785696],
       [0.802238  , 0.26651766],
       [0.09476241, 0.02178118]])

In [35]:
import numpy as np

# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[6, 6, 4],
       [0, 4, 3],
       [7, 0, 3]])

In [36]:
import numpy as np

# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
import numpy as np

# Repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
import numpy as np

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [39]:
import numpy as np

a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [40]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [41]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

print(a + 2)

[1 2 3 4]
[3 4 5 6]


In [42]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

print(a - 2)

[1 2 3 4]
[-1  0  1  2]


In [43]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

print(a * 2)

[1 2 3 4]
[2 4 6 8]


In [44]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

print(a / 2)

[1 2 3 4]
[0.5 1.  1.5 2. ]


In [45]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([1,0,1,0])

print(a)

print(b) 

print(a + b)

[1 2 3 4]
[1 0 1 0]
[2 2 4 4]


In [46]:
import numpy as np
a = np.array([1,2,3,4])

print(a)

print(a ** 2)

[1 2 3 4]
[ 1  4  9 16]


In [47]:
import numpy as np
a = np.array([1,2,3,4])

print(a)

# Take the sin
print(np.cos(a))

[1 2 3 4]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


##### Linear Algebra

In [48]:
import numpy as np

a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
import numpy as np

b = np.full((3,2), 2)
print(b)

print(np.matmul(a,b))

[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [50]:
import numpy as np

# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [51]:
import numpy as np
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [52]:
import numpy as np
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))

1


In [53]:
import numpy as np
stats = np.array([[1,2,3],[4,5,6]])
print(np.max(stats, axis=1))

[3 6]


In [54]:
import numpy as np
stats = np.array([[1,2,3],[4,5,6]])
print(np.sum(stats, axis=0))

[5 7 9]


### Reorganizing Arrays

In [57]:
import numpy as np

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:
# Vertically stacking vectors
import numpy as np

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [59]:
import numpy as np

# Horizontal  stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
